// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC23JnwxvRD_FyCRzdLzuzzCgC1iC0OyCA',
    appId: '1:496402561262:web:30880028742425504fdbff',
    messagingSenderId: '496402561262',
    projectId: 'chat-app-a412c',
    authDomain: 'chat-app-a412c.firebaseapp.com',
    storageBucket: 'chat-app-a412c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHrOx9ZNpEegiWKsF9QCGprDVPoNl4KhQ',
    appId: '1:496402561262:android:d137a850e19361cd4fdbff',
    messagingSenderId: '496402561262',
    projectId: 'chat-app-a412c',
    storageBucket: 'chat-app-a412c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYkRt1pXRY902B3vmXZ5tI_CVXh2sCVgI',
    appId: '1:496402561262:ios:335efe763504d47a4fdbff',
    messagingSenderId: '496402561262',
    projectId: 'chat-app-a412c',
    storageBucket: 'chat-app-a412c.firebasestorage.app',
    iosBundleId: 'com.example.google',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYkRt1pXRY902B3vmXZ5tI_CVXh2sCVgI',
    appId: '1:496402561262:ios:335efe763504d47a4fdbff',
    messagingSenderId: '496402561262',
    projectId: 'chat-app-a412c',
    storageBucket: 'chat-app-a412c.firebasestorage.app',
    iosBundleId: 'com.example.google',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC23JnwxvRD_FyCRzdLzuzzCgC1iC0OyCA',
    appId: '1:496402561262:web:7dd476d99efd431c4fdbff',
    messagingSenderId: '496402561262',
    projectId: 'chat-app-a412c',
    authDomain: 'chat-app-a412c.firebaseapp.com',
    storageBucket: 'chat-app-a412c.firebasestorage.app',
  );
}
